#%RAML 1.0 Library
traits:
  FiltrableEntreFechas:
    queryParameters:
      fechaDesde:
        type:
          - string
      fechaHasta:
        type:
          - string
  FiltrableEntreImportes:
    queryParameters:
      importeDesde:
        type:
          - string
      importeHasta:
        type:
          - string
