#%RAML 1.0 Library
types:
  Factura:
    properties:
      _id?: string
      tipo: string
      categoria?: string
      fecha: string
      importe: number
      movimientos: array
    example:
      _id: string
      tipo: ingreso
      categoria: ventas
      fecha: 2016-03-21
      importe: 123,45
      movimientos: |
        [
          '123','234'
        ]
