#%RAML 1.0 Library
types:
  Session:
    properties:
      _id?: string
      password?: string
      token?: string
    example:
      _id: a@b.c
      password: abc123
      token: 123sdf21as5df4a3s2df1ads5f421sdfasd
